### ISSUE TITLE
Version 3 checklist

### ISSUE THREAD

**Issue by juzraai** [juzraai/juzraai.github.io#6]
- [x] bs 4 custom theme
    - [ ] upgrade to beta 2 - http://getbootstrap.com/docs/4.0/migration/#beta-2-changes
- [x] minimal landing page
- [x] blog post design
- [x] ~~related post list~~ dropped for now
- [x] ~~blog list page with pagination~~ dropped for now
- [x] ~~blog search supporting tags too~~ dropped for now
    - [ ] ~~BUG: type a hashtag then clicking on tag link not working. but when I delete typed string, tag links working~~
- [x] activate jekyll-feed to serve rss
- [x] images
    - [x] og image
    - [x] fb cover
    - [x] logo/avatar
    - [x] favicon
    - [ ] ~~linkedin cover~~ dropped for now
- [x] configure jekyll-seo-tags to generate meta + json-ld
- [ ] post about new design - need rewrite to June 2018 release
    - [ ] colors, fonts
    - [ ] layout
    - [ ] content
    - [ ] screenshots of old site (landing pic into colors paragraph, post pic into fonts paragraph)
    - [ ] ~~actualize with BS 4b2, remove irrelevant, not interesting parts in whole post~~
- [x] ~~comments? (fb/disqus)~~ dropped for now
- [x] like/share buttons
- [x] portfolio (references, technologies)

Release checklist:

- [ ] ~~move redesign post from `_drafts` to `_posts`~~
- [ ] ~~merge `v3/bs4` into `v3/master`~~
- [ ] ~~merge `v3/master` into `master`~~
- [x] upload GH avatar
- [ ] upload gravatar
- [x] upload FB avatar
- [x] upload FB cover
- [x] trigger OG recrawl (using [debugger](https://developers.facebook.com/tools/debug/))
- [ ] publish redesign post on FB
